name: Build Electron App For Win/Mac

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: build and release electron app

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, macos-10.15]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      - name: NPM install
        run: |
          npm install

      - name: Build windows app
        if: matrix.os === 'windows-2019'
        run: |
          npm run package:win

      - name: Build mac app
        if: marix.os === 'macos-10.15'
        run: |
          npm run package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ martix.os }}
          path: release/build
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_API_KEY }}
